# Generated by Django 5.0.1 on 2026-01-05 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('calculated_balance', models.DecimalField(decimal_places=2, help_text='Saldo que debería haber según sistema', max_digits=10)),
                ('actual_balance', models.DecimalField(decimal_places=2, help_text='Saldo contado físicamente', max_digits=10)),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arqueo de Caja',
                'verbose_name_plural': 'Arqueos de Caja',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashCountDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Denominación')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total por denominación')),
                ('cash_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='petty_cash.cashcount')),
            ],
        ),
        migrations.CreateModel(
            name='PettyCashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_date', models.DateField(verbose_name='Fecha de Transacción')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Ingreso / Reembolso'), ('EXPENSE', 'Egreso / Gasto')], default='EXPENSE', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('concept', models.CharField(max_length=255, verbose_name='Concepto / Detalle del Pago')),
                ('beneficiary', models.CharField(blank=True, max_length=255, null=True, verbose_name='Beneficiario')),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='No. Comprobante / Factura')),
                ('service_order_ref', models.CharField(blank=True, max_length=50, null=True, verbose_name='Orden de Servicio (Ref)')),
                ('category_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código de Gasto')),
                ('nit', models.CharField(blank=True, max_length=20, null=True, verbose_name='NIT')),
                ('dui', models.CharField(blank=True, max_length=20, null=True, verbose_name='DUI')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Caja Chica',
                'verbose_name_plural': 'Movimientos de Caja Chica',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
