# Generated by Django 5.0.1 on 2026-01-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petty_cash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycashtransaction',
            name='nrc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NRC / Registro IVA'),
        ),
    ]
