# Generated by Django 5.0.1 on 2026-01-16 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petty_cash', '0002_pettycashtransaction_nrc'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashcount',
            name='sequence_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de Secuencia'),
        ),
        migrations.AddField(
            model_name='pettycashtransaction',
            name='cash_count',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='petty_cash.cashcount', verbose_name='Arqueo Asociado'),
        ),
    ]
