# Generated by Django 5.0.1 on 2025-12-08 01:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('VIEW', 'Ver'), ('EXPORT', 'Exportar'), ('LOGIN', 'Iniciar Sesión'), ('LOGOUT', 'Cerrar Sesión'), ('CLOSE_OS', 'Cerrar OS'), ('INVOICE', 'Facturar'), ('PAYMENT', 'Registrar Pago')], max_length=20, verbose_name='Acción')),
                ('model_name', models.CharField(max_length=100, verbose_name='Modelo/Tabla')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='ID del Objeto')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Representación del Objeto')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent (Navegador)')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Detalles Adicionales')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='users_audit_user_id_4b4ca5_idx'), models.Index(fields=['action', 'timestamp'], name='users_audit_action_962101_idx'), models.Index(fields=['model_name', 'object_id'], name='users_audit_model_n_fb8a47_idx'), models.Index(fields=['timestamp'], name='users_audit_timesta_45d1d4_idx')],
            },
        ),
    ]
