# Generated by Django 5.0.1 on 2025-12-14 14:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0002_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('error', 'Error'), ('success', 'Éxito')], default='info', max_length=20, verbose_name='Tipo')),
                ('category', models.CharField(choices=[('invoice', 'Facturación'), ('order', 'Órdenes de Servicio'), ('transfer', 'Transferencias'), ('client', 'Clientes'), ('payment', 'Pagos'), ('system', 'Sistema')], default='system', max_length=20, verbose_name='Categoría')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del Objeto')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creada')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Leída el')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Contenido')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='users_notif_user_id_f3f50a_idx'), models.Index(fields=['user', '-created_at'], name='users_notif_user_id_c37f16_idx'), models.Index(fields=['notification_type'], name='users_notif_notific_af6ddd_idx'), models.Index(fields=['category'], name='users_notif_categor_7f9fe2_idx')],
            },
        ),
    ]
