# Generated by Django 6.0 on 2025-12-07 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número de Orden')),
                ('purchase_order', models.CharField(max_length=100, verbose_name='PO (Purchase Order)')),
                ('eta', models.DateField(verbose_name='ETA')),
                ('duca', models.CharField(max_length=100, verbose_name='DUCA')),
                ('status', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client', verbose_name='Cliente')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.provider', verbose_name='Proveedor')),
                ('shipment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.shipmenttype', verbose_name='Tipo de Embarque')),
                ('sub_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.subclient', verbose_name='Subcliente')),
            ],
            options={
                'verbose_name': 'Orden de Servicio',
                'verbose_name_plural': 'Órdenes de Servicio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orders/docs/', verbose_name='Archivo')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='orders.serviceorder')),
            ],
            options={
                'verbose_name': 'Documento de Orden',
                'verbose_name_plural': 'Documentos de Ordenes',
            },
        ),
    ]
