# Generated by Django 5.0.1 on 2025-12-08 01:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_service_clientserviceprice'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='bl_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='BL/Referencia'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Cerrado por'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='customs_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.customsagent', verbose_name='Aforador'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='facturado',
            field=models.BooleanField(default=False, verbose_name='Facturado'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='mes',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='purchase_order',
            field=models.CharField(blank=True, max_length=100, verbose_name='PO (Purchase Order)'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Número de Factura')),
                ('invoice_type', models.CharField(choices=[('DTE', 'DTE (Documento Tributario Electrónico)'), ('FEX', 'FEX (Factura de Exportación)'), ('CCF', 'CCF (Comprobante de Crédito Fiscal)')], default='DTE', max_length=10, verbose_name='Tipo de Factura')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Emisión')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('subtotal_services', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Subtotal Servicios')),
                ('iva_services', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='IVA Servicios')),
                ('total_services', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total Servicios (con IVA)')),
                ('subtotal_third_party', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Subtotal Gastos a Terceros')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Factura')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Monto Pagado')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Saldo Pendiente')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('partial', 'Pago Parcial'), ('paid', 'Pagada'), ('cancelled', 'Anulada'), ('overdue', 'Vencida')], default='pending', max_length=20, verbose_name='Estado')),
                ('payment_condition', models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], default='credito', max_length=20, verbose_name='Condición de Pago')),
                ('dte_file', models.FileField(blank=True, null=True, upload_to='invoices/dte/', verbose_name='Archivo DTE')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/pdf/', verbose_name='PDF de Factura')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='orders.serviceorder', verbose_name='Orden de Servicio')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas (CXC)',
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('payment_method', models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta'), ('deposito', 'Depósito Bancario')], max_length=20, verbose_name='Método de Pago')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Número de Referencia/Cheque')),
                ('bank', models.CharField(blank=True, max_length=100, verbose_name='Banco')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='invoices/payments/', verbose_name='Comprobante de Pago')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.invoice', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Abono/Pago',
                'verbose_name_plural': 'Abonos/Pagos de Facturas',
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio Unitario (Sin IVA)')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal')),
                ('iva_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto IVA')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.service', verbose_name='Servicio')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='orders.serviceorder', verbose_name='Orden de Servicio')),
            ],
            options={
                'verbose_name': 'Cobro de OS',
                'verbose_name_plural': 'Cobros de OS',
                'ordering': ['service_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='orders_invo_invoice_4a2c44_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='orders_invo_status_b88bb2_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['service_order'], name='orders_invo_service_c145d9_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issue_date'], name='orders_invo_issue_d_239a92_idx'),
        ),
    ]
