# Generated by Django 5.0.1 on 2025-12-09 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_bank'),
        ('orders', '0002_serviceorder_bl_reference_serviceorder_closed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepayment',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.bank', verbose_name='Banco'),
        ),
    ]
