# Generated by Django 5.0.1 on 2025-12-11 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_invoice_retencion_and_file_validators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Documento de Orden', 'verbose_name_plural': 'Documentos de Ordenes'},
        ),
        migrations.AddField(
            model_name='orderdocument',
            name='document_type',
            field=models.CharField(choices=[('tramite', 'Documentos del Trámite'), ('factura_venta', 'Facturas de Venta'), ('factura_costo', 'Facturas de Costo / Comprobantes'), ('otros', 'Otros Documentos / Evidencias')], default='tramite', max_length=20, verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='orderdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por'),
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Orden Creada'), ('updated', 'Orden Actualizada'), ('status_changed', 'Cambio de Estado'), ('charge_added', 'Cobro Agregado'), ('charge_deleted', 'Cobro Eliminado'), ('payment_added', 'Pago a Proveedor Agregado'), ('payment_updated', 'Pago a Proveedor Actualizado'), ('payment_approved', 'Pago a Proveedor Aprobado'), ('payment_paid', 'Pago a Proveedor Ejecutado'), ('payment_deleted', 'Pago a Proveedor Eliminado'), ('document_uploaded', 'Documento Subido'), ('document_deleted', 'Documento Eliminado'), ('invoice_generated', 'Factura Generada'), ('invoice_payment', 'Pago de Cliente Recibido'), ('closed', 'Orden Cerrada'), ('reopened', 'Orden Reabierta')], max_length=30, verbose_name='Tipo de Evento')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Metadatos')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.serviceorder', verbose_name='Orden de Servicio')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Orden',
                'verbose_name_plural': 'Historial de Ordenes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service_order', '-created_at'], name='orders_orde_service_3160d4_idx'), models.Index(fields=['event_type'], name='orders_orde_event_t_dc56c2_idx')],
            },
        ),
    ]
