# Generated by Django 5.0.1 on 2025-12-13 01:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderdocument_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='ccf',
            field=models.CharField(blank=True, max_length=100, verbose_name='CCF (Comprobante de Crédito Fiscal)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de Emisión'),
        ),
    ]
