# Generated by Django 5.0.1 on 2025-12-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_invoice_ccf_alter_invoice_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercharge',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='ordercharge',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
    ]
