# Generated by Django 5.0.1 on 2025-12-13 21:44

import apps.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_ordercharge_deleted_at_ordercharge_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='credited_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Monto Acreditado (NC)'),
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('note_number', models.CharField(max_length=50, verbose_name='Número de NC')),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de Emisión')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Acreditado')),
                ('reason', models.CharField(max_length=255, verbose_name='Motivo')),
                ('pdf_file', models.FileField(blank=True, help_text='Solo PDF, JPG, PNG. Máximo 5MB', null=True, upload_to='invoices/credit_notes/', validators=[apps.validators.validate_document_file], verbose_name='PDF Nota Crédito')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='orders.invoice', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Nota de Crédito',
                'verbose_name_plural': 'Notas de Crédito',
                'ordering': ['-issue_date', '-id'],
            },
        ),
    ]
