# Generated by Django 5.0.1 on 2025-12-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_invoice_credited_amount_creditnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepayment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
    ]
