# Generated by Django 5.0.1 on 2025-12-13 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_invoicepayment_deleted_at_invoicepayment_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='orders.invoice', verbose_name='Factura'),
        ),
    ]
