# Generated by Django 5.0.1 on 2025-12-17 03:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_ordercharge_currency_ordercharge_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercharge',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Descuento (%)'),
        ),
    ]
