# Generated by Django 5.0.1 on 2025-12-17 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_ordercharge_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercharge',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='orders.invoice', verbose_name='Factura Asignada'),
        ),
    ]
