# Generated by Django 5.0.1 on 2025-12-18 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_ordercharge_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='dte_number',
            field=models.CharField(blank=True, help_text='Número de factura emitida en el sistema fiscal externo', max_length=100, verbose_name='Número DTE Real'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_dte_issued',
            field=models.BooleanField(default=False, help_text='Marcar cuando se emita la factura real en el sistema fiscal. Una vez marcado, solo se pueden hacer notas de crédito.', verbose_name='DTE Emitido'),
        ),
        migrations.CreateModel(
            name='InvoiceEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_type', models.CharField(choices=[('charge_added', 'Línea Agregada'), ('charge_edited', 'Línea Editada'), ('charge_removed', 'Línea Eliminada'), ('expense_edited', 'Gasto Editado'), ('totals_recalculated', 'Totales Recalculados'), ('dte_marked', 'Marcada como DTE Emitido')], max_length=30, verbose_name='Tipo de Edición')),
                ('description', models.TextField(verbose_name='Descripción del Cambio')),
                ('previous_values', models.JSONField(blank=True, null=True, verbose_name='Valores Anteriores')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='Valores Nuevos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='orders.invoice', verbose_name='Factura')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Edición de Factura',
                'verbose_name_plural': 'Historial de Ediciones de Facturas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invoice', '-created_at'], name='orders_invo_invoice_489898_idx')],
            },
        ),
    ]
