# Generated by Django - Manual Migration
# Optimización del Módulo de Calculadora de Cobros

from django.db import migrations, models
from decimal import Decimal


class Migration(migrations.Migration):
    """
    Migración para optimizar el módulo de Calculadora de Cobros.

    Cambios incluidos:
    1. OrderCharge: Agregar campos iva_type y billing_status
    2. Invoice: Agregar campos para desglose de IVA de gastos
    3. InvoiceEditHistory: Agregar nuevos tipos de edición
    """

    dependencies = [
        ('orders', '0015_billing_improvements'),
    ]

    operations = [
        # ============ ORDERCHARGE UPDATES ============
        # Agregar campo iva_type
        migrations.AddField(
            model_name='ordercharge',
            name='iva_type',
            field=models.CharField(
                choices=[
                    ('gravado', 'Gravado (13% IVA)'),
                    ('exento', 'Exento'),
                    ('no_sujeto', 'No Sujeto')
                ],
                default='gravado',
                max_length=20,
                verbose_name='Tratamiento Fiscal',
            ),
        ),
        # Agregar campo billing_status
        migrations.AddField(
            model_name='ordercharge',
            name='billing_status',
            field=models.CharField(
                choices=[
                    ('disponible', 'Disponible para Facturar'),
                    ('facturado', 'Facturado')
                ],
                default='disponible',
                max_length=20,
                verbose_name='Estado de Facturación',
            ),
        ),

        # ============ INVOICE UPDATES ============
        # Agregar campo iva_third_party
        migrations.AddField(
            model_name='invoice',
            name='iva_third_party',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                max_digits=15,
                verbose_name='IVA Gastos',
            ),
        ),
        # Agregar campo total_third_party
        migrations.AddField(
            model_name='invoice',
            name='total_third_party',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                max_digits=15,
                verbose_name='Total Gastos',
            ),
        ),
        # Agregar campo subtotal_neto
        migrations.AddField(
            model_name='invoice',
            name='subtotal_neto',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                max_digits=15,
                verbose_name='Subtotal Neto (Sin IVA)',
            ),
        ),
        # Agregar campo iva_total
        migrations.AddField(
            model_name='invoice',
            name='iva_total',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                max_digits=15,
                verbose_name='IVA Total',
            ),
        ),
    ]
