# Generated by Django 5.0.1 on 2025-12-21 04:02

from decimal import Decimal
from django.db import migrations, models


def update_ccf_to_dte(apps, schema_editor):
    """
    Migración de datos: Convertir facturas CCF a DTE
    CCF ya no existe, ahora el tipo estándar es DTE
    """
    Invoice = apps.get_model('orders', 'Invoice')
    updated_count = Invoice.objects.filter(invoice_type='CCF').update(invoice_type='DTE')
    if updated_count > 0:
        print(f"OK - Se actualizaron {updated_count} facturas de 'CCF' a 'DTE'")


def reverse_update(apps, schema_editor):
    """Operación reversa: No hacemos nada porque CCF desaparecerá"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_optimize_billing_calculator'),
    ]

    operations = [
        # Primero migrar los datos
        migrations.RunPython(update_ccf_to_dte, reverse_update),

        # Luego cambiar el campo
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('DTE', 'DTE (Documento Tributario Electrónico)'), ('FEX', 'FEX (Factura de Exportación)'), ('INTL', 'Factura Internacional')], default='DTE', max_length=10, verbose_name='Tipo de Factura'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal_services',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Subtotal Servicios (Neto)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal_third_party',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Subtotal Gastos (Neto)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_services',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total Servicios'),
        ),
        migrations.AlterField(
            model_name='invoiceedithistory',
            name='edit_type',
            field=models.CharField(choices=[('charge_added', 'Línea de Servicio Agregada'), ('charge_edited', 'Línea de Servicio Editada'), ('charge_removed', 'Línea de Servicio Removida'), ('expense_added', 'Gasto Agregado'), ('expense_edited', 'Gasto Editado'), ('expense_removed', 'Gasto Removido'), ('markup_changed', 'Margen de Utilidad Modificado'), ('iva_type_changed', 'Tipo de IVA Modificado'), ('iva_toggle_changed', 'Aplicación de IVA Modificada'), ('totals_recalculated', 'Totales Recalculados'), ('dte_marked', 'Marcada como DTE Emitido'), ('synced_from_os', 'Sincronizado desde OS'), ('synced_to_os', 'Sincronizado hacia OS')], max_length=30, verbose_name='Tipo de Edición'),
        ),
    ]
