# Generated by Django 5.0.1 on 2025-12-21 14:15

from django.db import migrations, models


def update_exento_to_gravado(apps, schema_editor):
    """
    Migración de datos: Convertir todos los OrderCharge con iva_type='exento' a 'gravado'
    ya que la opción 'exento' se ha eliminado del sistema.
    """
    OrderCharge = apps.get_model('orders', 'OrderCharge')
    updated_count = OrderCharge.objects.filter(iva_type='exento').update(iva_type='gravado')
    if updated_count > 0:
        print(f"OK - Se actualizaron {updated_count} cargos de 'exento' a 'gravado'")


def reverse_update(apps, schema_editor):
    """Operación reversa: No hacemos nada porque exento desaparecerá"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_update_ccf_to_dte_invoice_type'),
    ]

    operations = [
        # Primero migrar los datos
        migrations.RunPython(update_exento_to_gravado, reverse_update),

        # Luego cambiar el campo
        migrations.AlterField(
            model_name='ordercharge',
            name='iva_type',
            field=models.CharField(choices=[('gravado', 'Gravado (13% IVA)'), ('no_sujeto', 'No Sujeto')], default='gravado', max_length=20, verbose_name='Tratamiento Fiscal'),
        ),
    ]
