# Generated by Django 5.0.1 on 2025-12-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_update_service_order_status_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercharge',
            name='currency',
            field=models.CharField(choices=[('USD', 'Dólares (USD)'), ('GTQ', 'Quetzales (GTQ)')], default='USD', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='duca',
            field=models.CharField(blank=True, max_length=100, verbose_name='DUCA'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='eta',
            field=models.DateField(blank=True, null=True, verbose_name='ETA'),
        ),
    ]
