# Generated by Django 5.0.1 on 2026-01-03 20:50

import apps.validators
import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_make_eta_duca_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditnote',
            options={'ordering': ['-issue_date', '-id'], 'verbose_name': 'Nota de Credito', 'verbose_name_plural': 'Notas de Credito'},
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de Emision'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='note_number',
            field=models.CharField(max_length=50, verbose_name='Numero de NC'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Solo PDF, JPG, PNG. Maximo 5MB', null=True, upload_to='invoices/credit_notes/', validators=[apps.validators.validate_document_file], verbose_name='PDF Nota Credito'),
        ),
        migrations.AlterField(
            model_name='ordercharge',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Descuento (%)'),
        ),
        migrations.AlterField(
            model_name='ordercharge',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio Unitario (Sin IVA)'),
        ),
    ]
