# Generated by Django 5.0.1 on 2026-01-03 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0014_add_customs_model'),
        ('orders', '0021_add_notes_to_serviceorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='customs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.customs', verbose_name='Aduana'),
        ),
    ]
