# Generated by Django 5.0.1 on 2026-01-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_add_customs_to_serviceorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercharge',
            name='is_third_party_service',
            field=models.BooleanField(default=False, help_text='Si es True, este servicio tiene un costo directo asociado (ProviderInvoice)', verbose_name='Servicio Tercerizado'),
        ),
    ]
