# Generated by Django 5.0.1 on 2026-01-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_billing_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercharge',
            name='iva_type',
            field=models.CharField(choices=[('gravado', 'Gravado (13% IVA)'), ('exento', 'Exento'), ('no_sujeto', 'No Sujeto')], default='gravado', max_length=20, verbose_name='Tratamiento Fiscal'),
        ),
    ]
