# Generated by Django 5.0.1 on 2026-01-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_alter_ordercharge_iva_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='dte_issued_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se marcó como DTE emitido. Permite eliminación durante 24 horas.', null=True, verbose_name='Fecha de Emisión DTE'),
        ),
    ]
