# Generated by Django 5.0.1 on 2026-01-04 18:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_add_dte_issued_timestamp'),
        ('transfers', '0017_billing_refactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentItemAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Asignado')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='orders.ordercharge', verbose_name='Servicio')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='transfers.transfer', verbose_name='Gasto')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_allocations', to='orders.invoicepayment', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Asignación de Pago por Item',
                'verbose_name_plural': 'Asignaciones de Pago por Item',
                'ordering': ['payment', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='paymentitemallocation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('charge__isnull', False), ('expense__isnull', True)), models.Q(('charge__isnull', True), ('expense__isnull', False)), _connector='OR'), name='payment_allocation_one_item_type'),
        ),
    ]
