# Generated by Django 5.0.1 on 2026-01-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_payment_item_allocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='event_type',
            field=models.CharField(choices=[('created', 'Orden Creada'), ('updated', 'Orden Actualizada'), ('status_changed', 'Cambio de Estado'), ('charge_added', 'Cobro Agregado'), ('charge_updated', 'Cobro Actualizado'), ('charge_deleted', 'Cobro Eliminado'), ('payment_added', 'Pago a Proveedor Agregado'), ('payment_updated', 'Pago a Proveedor Actualizado'), ('payment_approved', 'Pago a Proveedor Aprobado'), ('payment_paid', 'Pago a Proveedor Ejecutado'), ('payment_deleted', 'Pago a Proveedor Eliminado'), ('document_uploaded', 'Documento Subido'), ('document_deleted', 'Documento Eliminado'), ('invoice_generated', 'Factura Generada'), ('invoice_payment', 'Pago de Cliente Recibido'), ('invoice_payment_deleted', 'Pago de Cliente Eliminado'), ('invoice_voided', 'Factura Anulada'), ('credit_note_added', 'Nota de Crédito Aplicada'), ('closed', 'Orden Cerrada'), ('reopened', 'Orden Reabierta')], max_length=30, verbose_name='Tipo de Evento'),
        ),
    ]
