# Generated by Django 5.0.1 on 2026-01-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_alter_orderhistory_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='is_manual_os',
            field=models.BooleanField(default=False, help_text='Permite ingresar número de OS manualmente (solo para años anteriores)', verbose_name='OS Manual'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Número de Orden'),
        ),
    ]
