# Generated by Django 5.0.1 on 2026-01-10 20:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0014_add_customs_model'),
        ('clients', '0008_add_client_type'),
        ('orders', '0028_serviceorder_is_manual_os_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['order_number'], name='orders_serv_order_n_96796a_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['status'], name='orders_serv_status_671e42_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['client'], name='orders_serv_client__baa1b0_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['created_at'], name='orders_serv_created_4be71f_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['facturado'], name='orders_serv_factura_787ed1_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['-created_at', 'status'], name='orders_serv_created_f3a6d4_idx'),
        ),
    ]
