# Generated by Django 5.0.1 on 2026-01-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_add_serviceorder_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='duca',
            field=models.CharField(blank=True, max_length=1000, verbose_name='DUCA'),
        ),
    ]
