# Generated by Django 5.0.1 on 2026-01-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_increase_duca_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='duca',
            field=models.CharField(blank=True, max_length=5000, verbose_name='DUCA'),
        ),
    ]
