# Generated by Django 5.0.1 on 2026-01-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_alter_serviceorder_duca'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='generation_code',
            field=models.CharField(blank=True, help_text='Código único de generación del DTE (MH)', max_length=150, verbose_name='Código de Generación'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reception_stamp',
            field=models.CharField(blank=True, help_text='Sello de recepción otorgado por Hacienda', max_length=150, verbose_name='Sello de Recepción'),
        ),
    ]
