# Generated by Django 4.2.27 on 2026-01-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_invoice_generation_code_invoice_reception_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepayment',
            name='numero_comprobante_retencion',
            field=models.CharField(blank=True, help_text='Número del comprobante de retención emitido por el Gran Contribuyente', max_length=50, verbose_name='Número Comprobante F-910'),
        ),
        migrations.AlterField(
            model_name='invoicepayment',
            name='payment_method',
            field=models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta'), ('deposito', 'Depósito Bancario'), ('retencion', 'Comprobante de Retención F-910')], max_length=20, verbose_name='Método de Pago'),
        ),
    ]
