# Generated by Django 5.0.1 on 2026-01-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_invoicepayment_numero_comprobante_retencion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepayment',
            name='retention_generation_code',
            field=models.CharField(blank=True, max_length=150, verbose_name='Código Generación Retención'),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='retention_reception_stamp',
            field=models.CharField(blank=True, max_length=150, verbose_name='Sello Recepción Retención'),
        ),
        migrations.AlterField(
            model_name='invoicepayment',
            name='numero_comprobante_retencion',
            field=models.CharField(blank=True, help_text='Número del comprobante de retención emitido por el Gran Contribuyente', max_length=50, verbose_name='Número Comprobante de Retención'),
        ),
    ]
