# Generated by Django 5.0.1 on 2026-01-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_invoicepayment_retention_generation_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='is_manual_os',
            field=models.BooleanField(default=False, help_text='Permite ingresar número de OS manualmente', verbose_name='OS Manual'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Número de Orden'),
        ),
    ]
