# Generated by Django 5.0.1 on 2026-03-06 01:19

import re
from django.db import migrations


def fix_description_keys(apps, schema_editor):
    """
    Migra los OrderDocument existentes al nuevo formato de claves exactas
    para evitar coincidencias parciales entre IDs.
    Ej: 'Transfer-42' -> '[Transfer:42]'
    """
    OrderDocument = apps.get_model('orders', 'OrderDocument')

    # Fix Transfer-N format -> [Transfer:N]
    for doc in OrderDocument.objects.filter(description__contains='Transfer-').exclude(description__contains='[Transfer:'):
        match = re.search(r'Transfer-(\d+)', doc.description)
        if match:
            transfer_id = match.group(1)
            old_key = f'Transfer-{transfer_id}'
            new_key = f'[Transfer:{transfer_id}]'
            doc.description = doc.description.replace(old_key, new_key)
            doc.save(update_fields=['description'])

    # Fix Lote format -> [Lote:number]
    for doc in OrderDocument.objects.filter(description__contains='Lote ').exclude(description__contains='[Lote:'):
        match = re.search(r'Lote (\S+)', doc.description)
        if match:
            batch_number = match.group(1).rstrip(' -')
            new_key = f'[Lote:{batch_number}]'
            doc.description = doc.description + f' {new_key}'
            doc.save(update_fields=['description'])

    # Fix NC- format -> [NC:number]
    for doc in OrderDocument.objects.filter(description__contains='NC-').exclude(description__contains='[NC:'):
        match = re.search(r'(?<!\[)NC-(\S+)', doc.description)
        if match:
            nc_number = match.group(1)
            new_key = f'[NC:{nc_number}]'
            doc.description = doc.description + f' {new_key}'
            doc.save(update_fields=['description'])

    # Fix invalid document_type
    OrderDocument.objects.filter(document_type='pago_proveedor').update(document_type='factura_costo')


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_alter_serviceorder_is_manual_os_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_description_keys, migrations.RunPython.noop),
    ]
