# Generated by Django 6.0 on 2025-12-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre / Razón Social')),
                ('nit', models.CharField(max_length=50, verbose_name='NIT')),
                ('iva_registration', models.CharField(max_length=50, verbose_name='Registro IVA')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('payment_condition', models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], max_length=20, verbose_name='Condición de Pago')),
                ('credit_days', models.IntegerField(default=0, verbose_name='Días de Crédito')),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Límite de Crédito')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
