# Generated by Django 5.0.1 on 2025-12-09 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_add_client_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre Jurídico Completo'),
        ),
        migrations.AddField(
            model_name='client',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono Secundario'),
        ),
    ]
