# Generated by Django 5.0.1 on 2025-12-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_is_gran_contribuyente'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='taxpayer_type',
            field=models.CharField(choices=[('grande', 'Gran Contribuyente'), ('mediano', 'Mediano Contribuyente'), ('pequeno', 'Pequeño Contribuyente')], default='pequeno', help_text='Clasificación según la Dirección General de Impuestos Internos de El Salvador', max_length=20, verbose_name='Clasificación de Contribuyente'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_gran_contribuyente',
            field=models.BooleanField(default=False, verbose_name='Gran Contribuyente (Legacy)'),
        ),
    ]
