# Generated by Django 5.0.1 on 2025-12-25 23:47

from django.db import migrations


def sync_taxpayer_type_from_legacy(apps, schema_editor):
    """
    Sincroniza el nuevo campo taxpayer_type basado en el campo legacy is_gran_contribuyente.

    - Si is_gran_contribuyente=True -> taxpayer_type='grande'
    - Si is_gran_contribuyente=False -> taxpayer_type='pequeno' (default conservador)
    """
    Client = apps.get_model('clients', 'Client')

    # Actualizar Gran Contribuyentes
    Client.objects.filter(is_gran_contribuyente=True).update(taxpayer_type='grande')

    # Los demás quedan como 'pequeno' (default del campo)


def reverse_sync(apps, schema_editor):
    """Reversa: restaurar is_gran_contribuyente desde taxpayer_type"""
    Client = apps.get_model('clients', 'Client')

    Client.objects.filter(taxpayer_type='grande').update(is_gran_contribuyente=True)
    Client.objects.exclude(taxpayer_type='grande').update(is_gran_contribuyente=False)


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_add_taxpayer_type_classification'),
    ]

    operations = [
        migrations.RunPython(sync_taxpayer_type_from_legacy, reverse_sync),
    ]
