# Generated by Django 5.0.1 on 2025-12-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_sync_taxpayer_type_from_legacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='client',
            name='iva_registration',
            field=models.CharField(blank=True, max_length=50, verbose_name='Registro IVA'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nit',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='NIT'),
        ),
    ]
