# Generated by Django 5.0.1 on 2026-01-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_client_address_alter_client_iva_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('nacional', 'Nacional'), ('internacional', 'Internacional')], default='nacional', help_text='Nacional: Cliente local de El Salvador. Internacional: Cliente extranjero.', max_length=20, verbose_name='Tipo de Cliente'),
        ),
    ]
