# Generated by Django 5.0.1 on 2025-12-08 01:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_add_catalog_fields'),
        ('clients', '0002_add_client_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Servicio')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio por Defecto (Sin IVA)')),
                ('applies_iva', models.BooleanField(default=True, verbose_name='Aplica IVA')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['code', 'name'],
                'indexes': [models.Index(fields=['code'], name='catalogs_se_code_a1cd96_idx'), models.Index(fields=['is_active'], name='catalogs_se_is_acti_46b361_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClientServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio Personalizado (Sin IVA)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Vigencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_prices', to='clients.client', verbose_name='Cliente')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_prices', to='catalogs.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Precio Personalizado',
                'verbose_name_plural': 'Tarifario de Clientes',
                'ordering': ['client__name', 'service__code'],
                'indexes': [models.Index(fields=['client', 'service'], name='catalogs_cl_client__3d676d_idx'), models.Index(fields=['is_active'], name='catalogs_cl_is_acti_1ed59f_idx')],
                'unique_together': {('client', 'service')},
            },
        ),
    ]
