# Generated by Django 5.0.1 on 2025-12-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_service_clientserviceprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Banco')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('swift_code', models.CharField(blank=True, max_length=11, verbose_name='Código SWIFT')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de Contacto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='catalogs_ba_code_346d0b_idx'), models.Index(fields=['is_active'], name='catalogs_ba_is_acti_4d1035_idx')],
            },
        ),
    ]
