# Generated by Django 5.0.1 on 2025-12-10 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_bank'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bank',
            name='catalogs_ba_code_346d0b_idx',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='code',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='swift_code',
        ),
    ]
