# Generated by Django 5.0.1 on 2025-12-10 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0005_remove_bank_catalogs_ba_code_346d0b_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customsagent',
            name='code',
        ),
    ]
