# Generated by Django 5.0.1 on 2025-12-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0006_remove_customsagent_code'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='service',
            name='catalogs_se_code_a1cd96_idx',
        ),
        migrations.RemoveField(
            model_name='service',
            name='code',
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['name'], name='catalogs_se_name_8f9a1b_idx'),
        ),
    ]
