# Generated by Django 5.0.1 on 2025-12-10 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0007_remove_service_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientserviceprice',
            options={'ordering': ['client__name', 'service__name'], 'verbose_name': 'Precio Personalizado', 'verbose_name_plural': 'Tarifario de Clientes'},
        ),
        migrations.RenameIndex(
            model_name='service',
            new_name='catalogs_se_name_c9372a_idx',
            old_name='catalogs_se_name_8f9a1b_idx',
        ),
    ]
