# Generated by Django - Manual Migration
# Agregar campo iva_type al modelo Service

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migración para agregar el campo iva_type al modelo Service.

    Tratamiento fiscal según Ministerio de Hacienda El Salvador:
    - GRAVADO: IVA 13%
    - EXENTO: Sin IVA
    - NO_SUJETO: Sin IVA (exportaciones)
    """

    dependencies = [
        ('catalogs', '0009_providercategory_provider_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='iva_type',
            field=models.CharField(
                choices=[
                    ('gravado', 'Gravado (13% IVA)'),
                    ('exento', 'Exento'),
                    ('no_sujeto', 'No Sujeto')
                ],
                default='gravado',
                help_text='Tipo de IVA según normativa salvadoreña',
                max_length=20,
                verbose_name='Tratamiento Fiscal',
            ),
        ),
    ]
