# Generated by Django 4.2.27 on 2025-12-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0010_service_iva_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientserviceprice',
            name='iva_type',
            field=models.CharField(blank=True, choices=[('gravado', 'Gravado (13% IVA)'), ('exento', 'Exento'), ('no_sujeto', 'No Sujeto')], help_text='Si se deja vacío, se usará la configuración del servicio general.', max_length=20, null=True, verbose_name='Tratamiento Fiscal Personalizado'),
        ),
        migrations.AlterField(
            model_name='service',
            name='iva_type',
            field=models.CharField(choices=[('gravado', 'Gravado (13% IVA)'), ('exento', 'Exento'), ('no_sujeto', 'No Sujeto')], default='gravado', max_length=20, verbose_name='Tratamiento Fiscal'),
        ),
    ]
