# Generated by Django 5.0.1 on 2026-01-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0013_update_shipment_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Código')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Ubicación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Aduana',
                'verbose_name_plural': 'Aduanas',
                'ordering': ['name'],
            },
        ),
    ]
