# Generated by Django 6.0 on 2025-12-07 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('terceros', 'Cargos a Clientes (Terceros)'), ('propios', 'Costos Operativos (Propios)'), ('admin', 'Gastos Administrativos')], max_length=20, verbose_name='Tipo de Gasto')),
                ('status', models.CharField(choices=[('provisionada', 'Provisionada'), ('pagada', 'Pagada')], default='provisionada', max_length=20, verbose_name='Estado')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='transfers/invoices/', verbose_name='Factura')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('service_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='orders.serviceorder', verbose_name='Orden de Servicio')),
            ],
            options={
                'verbose_name': 'Transferencia / Gasto',
                'verbose_name_plural': 'Transferencias y Gastos',
            },
        ),
    ]
