# Generated by Django 5.0.1 on 2025-12-08 01:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_service_clientserviceprice'),
        ('clients', '0002_add_client_fields'),
        ('orders', '0002_serviceorder_bl_reference_serviceorder_closed_at_and_more'),
        ('transfers', '0002_add_transfer_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='bank',
            field=models.CharField(blank=True, max_length=100, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='beneficiary_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='A Nombre De (Beneficiario)'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='ccf',
            field=models.CharField(blank=True, max_length=100, verbose_name='CCF (Número de Factura)'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='mes',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mes'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número de Factura/Comprobante'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Transacción'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['transfer_type', 'status'], name='transfers_t_transfe_77b45c_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['transaction_date'], name='transfers_t_transac_988a48_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['service_order'], name='transfers_t_service_81638d_idx'),
        ),
    ]
