# Generated by Django 5.0.1 on 2025-12-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0005_transfer_invoice_file_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('pagado', 'Pagado'), ('provisionada', 'Provisionada (Legacy)')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_type',
            field=models.CharField(choices=[('costos', 'Costos Directos'), ('cargos', 'Cargos a Clientes'), ('admin', 'Gastos de Operación'), ('terceros', 'Cargos a Clientes (Legacy)'), ('propios', 'Costos Operativos (Legacy)')], max_length=20, verbose_name='Tipo de Gasto'),
        ),
    ]
