# Generated by Django 5.0.1 on 2025-12-13 22:48

import apps.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0006_alter_transfer_status_alter_transfer_transfer_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Saldo Pendiente'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Monto Pagado'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto Total'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago (Ultimo)'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta'), ('nota_credito', 'Nota de Crédito')], max_length=20, verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('parcial', 'Pago Parcial'), ('pagado', 'Pagado'), ('provisionada', 'Provisionada (Legacy)')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='TransferPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Pagado')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Pago')),
                ('payment_method', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta'), ('nota_credito', 'Nota de Crédito')], max_length=20, verbose_name='Método de Pago')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Referencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='transfers/payments/', validators=[apps.validators.validate_document_file], verbose_name='Comprobante de Pago')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='transfers.transfer', verbose_name='Transferencia/Gasto')),
            ],
            options={
                'verbose_name': 'Pago a Proveedor',
                'verbose_name_plural': 'Pagos a Proveedores',
                'ordering': ['-payment_date'],
            },
        ),
    ]
