# Generated by Django 5.0.1 on 2025-12-16 03:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0007_transfer_balance_transfer_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='currency',
            field=models.CharField(choices=[('GTQ', 'Quetzales (GTQ)'), ('USD', 'Dólares (USD)')], default='GTQ', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Tipo de Cambio'),
        ),
    ]
