# Generated by Django 5.0.1 on 2025-12-17 04:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0008_transfer_currency_transfer_exchange_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='notes',
        ),
        migrations.AddField(
            model_name='transfer',
            name='customer_applies_iva',
            field=models.BooleanField(default=False, verbose_name='Aplica IVA Cliente'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='customer_markup_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Margen Cobro Cliente %'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
