# Generated by Django 5.0.1 on 2025-12-18 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_billing_improvements'),
        ('transfers', '0009_remove_transfer_notes_transfer_customer_applies_iva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Factura donde se cobró este gasto al cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billed_transfers', to='orders.invoice', verbose_name='Factura Asociada'),
        ),
    ]
