# Generated by Django - Manual Migration
# Optimización del Módulo de Calculadora de Gastos Reembolsables

from django.db import migrations, models
from decimal import Decimal


class Migration(migrations.Migration):
    """
    Migración para optimizar la Calculadora de Gastos Reembolsables.

    Cambios incluidos:
    1. Transfer: Agregar campos customer_iva_type, billing_status, amount_locked
    """

    dependencies = [
        ('transfers', '0010_billing_improvements'),
    ]

    operations = [
        # ============ TRANSFER UPDATES ============
        # Agregar campo customer_iva_type
        migrations.AddField(
            model_name='transfer',
            name='customer_iva_type',
            field=models.CharField(
                choices=[
                    ('gravado', 'Gravado (13% IVA)'),
                    ('exento', 'Exento'),
                    ('no_sujeto', 'No Sujeto')
                ],
                default='exento',
                help_text='Tipo de IVA a aplicar al cobrar este gasto al cliente',
                max_length=20,
                verbose_name='Tratamiento Fiscal Cliente',
            ),
        ),
        # Agregar campo billing_status
        migrations.AddField(
            model_name='transfer',
            name='billing_status',
            field=models.CharField(
                choices=[
                    ('disponible', 'Disponible para Facturar'),
                    ('facturado', 'Facturado')
                ],
                default='disponible',
                max_length=20,
                verbose_name='Estado de Facturación',
            ),
        ),
        # Agregar campo amount_locked
        migrations.AddField(
            model_name='transfer',
            name='amount_locked',
            field=models.BooleanField(
                default=False,
                help_text='Si True, el monto base no puede editarse (viene del pago a proveedor)',
                verbose_name='Monto Base Bloqueado',
            ),
        ),
    ]
