# Generated by Django 5.0.1 on 2025-12-21 02:58

from django.db import migrations, models


def update_exento_to_no_sujeto(apps, schema_editor):
    """
    Migración de datos: Convertir todos los registros con customer_iva_type='exento' a 'no_sujeto'
    ya que la opción 'exento' se ha eliminado del sistema.
    """
    Transfer = apps.get_model('transfers', 'Transfer')
    updated_count = Transfer.objects.filter(customer_iva_type='exento').update(customer_iva_type='no_sujeto')
    if updated_count > 0:
        print(f"OK - Se actualizaron {updated_count} registros de 'exento' a 'no_sujeto'")


def reverse_update(apps, schema_editor):
    """Operación reversa: volver de 'no_sujeto' a 'exento' (solo si es necesario revertir)"""
    # No hacemos nada en el reverso porque no podemos distinguir cuáles eran originalmente 'exento'
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0011_optimize_expense_calculator'),
    ]

    operations = [
        # Primero actualizar los datos
        migrations.RunPython(update_exento_to_no_sujeto, reverse_update),

        # Luego cambiar el campo
        migrations.AlterField(
            model_name='transfer',
            name='customer_applies_iva',
            field=models.BooleanField(default=False, verbose_name='Aplica IVA Cliente (Legacy)'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='customer_iva_type',
            field=models.CharField(choices=[('gravado', 'Gravado (13% IVA)'), ('no_sujeto', 'No Sujeto (Exportación)')], default='no_sujeto', help_text='Tipo de IVA a aplicar al cobrar este gasto al cliente', max_length=20, verbose_name='Tratamiento Fiscal Cliente'),
        ),
    ]
