# Generated by Django 5.0.1 on 2025-12-22 04:34

import apps.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0011_clientserviceprice_iva_type_alter_service_iva_type'),
        ('transfers', '0012_update_exento_to_no_sujeto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('batch_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número de Lote')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Total del Pago')),
                ('payment_method', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta'), ('nota_credito', 'Nota de Crédito')], max_length=20, verbose_name='Método de Pago')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Pago')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Número de Referencia')),
                ('proof_file', models.FileField(blank=True, help_text='Este comprobante se asociará a todas las facturas incluidas en el lote', null=True, upload_to='transfers/batch_payments/', validators=[apps.validators.validate_document_file], verbose_name='Comprobante de Pago')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.bank', verbose_name='Banco')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.provider', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Pago Agrupado',
                'verbose_name_plural': 'Pagos Agrupados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transferpayment',
            name='batch_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_payments', to='transfers.batchpayment', verbose_name='Pago Agrupado'),
        ),
        migrations.AddIndex(
            model_name='batchpayment',
            index=models.Index(fields=['provider', 'payment_date'], name='transfers_b_provide_7e9f10_idx'),
        ),
        migrations.AddIndex(
            model_name='batchpayment',
            index=models.Index(fields=['batch_number'], name='transfers_b_batch_n_358520_idx'),
        ),
    ]
