# Generated by Django 5.0.1 on 2025-12-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0013_batchpayment_transferpayment_batch_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='currency',
            field=models.CharField(choices=[('USD', 'Dólares (USD)'), ('GTQ', 'Quetzales (GTQ)')], default='USD', max_length=3, verbose_name='Moneda'),
        ),
    ]
