# Generated by Django 5.0.1 on 2025-12-27 20:39

import apps.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0013_update_shipment_types'),
        ('transfers', '0014_alter_transfer_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('note_number', models.CharField(help_text='Número fiscal de la NC emitida por el proveedor', max_length=100, verbose_name='Número de Nota de Crédito')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Total NC')),
                ('applied_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Suma de montos aplicados a facturas', max_digits=15, verbose_name='Monto Aplicado')),
                ('available_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto pendiente de aplicar', max_digits=15, verbose_name='Saldo Disponible')),
                ('issue_date', models.DateField(help_text='Fecha en que el proveedor emitió la NC', verbose_name='Fecha de Emisión')),
                ('received_date', models.DateField(default=django.utils.timezone.now, help_text='Fecha en que se recibió la NC', verbose_name='Fecha de Recepción')),
                ('reason', models.CharField(choices=[('devolucion', 'Devolución de Mercancía'), ('descuento', 'Descuento Comercial'), ('error_factura', 'Error en Factura Original'), ('bonificacion', 'Bonificación'), ('ajuste_precio', 'Ajuste de Precio'), ('garantia', 'Reclamo por Garantía'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Motivo')),
                ('reason_detail', models.TextField(blank=True, verbose_name='Detalle del Motivo')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente de Aplicar'), ('parcial', 'Aplicada Parcialmente'), ('aplicada', 'Aplicada Totalmente'), ('anulada', 'Anulada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='transfers/credit_notes/', validators=[apps.validators.validate_document_file], verbose_name='Documento PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Anulación')),
                ('void_reason', models.TextField(blank=True, verbose_name='Motivo de Anulación')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_credit_notes_created', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='catalogs.provider', verbose_name='Proveedor')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_credit_notes_voided', to=settings.AUTH_USER_MODEL, verbose_name='Anulado por')),
            ],
            options={
                'verbose_name': 'Nota de Crédito de Proveedor',
                'verbose_name_plural': 'Notas de Crédito de Proveedores',
                'ordering': ['-issue_date', '-created_at'],
                'unique_together': {('provider', 'note_number')},
            },
        ),
        migrations.CreateModel(
            name='CreditNoteApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Aplicado')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Aplicación')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('applied_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Aplicado por')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_note_applications', to='transfers.transfer', verbose_name='Factura/Gasto')),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='transfers.providercreditnote', verbose_name='Nota de Crédito')),
            ],
            options={
                'verbose_name': 'Aplicación de NC',
                'verbose_name_plural': 'Aplicaciones de NC',
                'ordering': ['-applied_at'],
            },
        ),
    ]
