# Generated by Django 5.0.1 on 2025-12-27 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0015_add_provider_credit_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='providercreditnote',
            name='original_transfer',
            field=models.ForeignKey(blank=True, help_text='Factura del proveedor a la que aplica esta NC', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='transfers.transfer', verbose_name='Factura Original'),
        ),
    ]
