# Generated by Django 5.0.1 on 2026-01-04 03:20

import apps.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0014_add_customs_model'),
        ('orders', '0023_billing_refactor'),
        ('transfers', '0016_add_original_transfer_to_credit_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='is_pass_through',
            field=models.BooleanField(default=False, help_text='La factura original está a nombre del cliente. Se factura NETO sin margen.', verbose_name='Es Reembolso (Pass-through)'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_type',
            field=models.CharField(choices=[('cargos', 'Cargos a Clientes (Reembolso)'), ('admin', 'Gastos de Operación'), ('costos', 'Costos Directos (Legacy)'), ('terceros', 'Cargos a Clientes (Legacy)'), ('propios', 'Costos Operativos (Legacy)')], max_length=20, verbose_name='Tipo de Gasto'),
        ),
        migrations.CreateModel(
            name='ProviderInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('invoice_number', models.CharField(help_text='Número de la factura emitida por el proveedor', max_length=100, verbose_name='No. Factura Proveedor')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Total Factura')),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Monto Asignado a Servicios')),
                ('unallocated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Monto Sin Asignar')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente de Asignar'), ('parcial', 'Parcialmente Asignado'), ('asignado', 'Completamente Asignado'), ('facturado', 'Servicios Facturados al Cliente')], default='pendiente', max_length=20, verbose_name='Estado de Asignación')),
                ('payment_status', models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('parcial', 'Pago Parcial'), ('pagado', 'Pagado')], default='pendiente', max_length=20, verbose_name='Estado de Pago')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Monto Pagado')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='provider_invoices/', validators=[apps.validators.validate_document_file], verbose_name='Archivo de Factura')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Emisión')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_provider_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_cost_invoices', to='catalogs.provider', verbose_name='Proveedor')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_invoices', to='orders.serviceorder', verbose_name='Orden de Servicio')),
            ],
            options={
                'verbose_name': 'Factura de Proveedor (Costo Directo)',
                'verbose_name_plural': 'Facturas de Proveedores (Costos Directos)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectCostAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('cost_amount', models.DecimalField(decimal_places=2, help_text='Porción del costo de la factura asignada a este servicio', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Costo Asignado')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción del Desglose')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('order_charge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_allocation', to='orders.ordercharge', verbose_name='Servicio Vinculado')),
                ('provider_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='transfers.providerinvoice', verbose_name='Factura de Proveedor')),
            ],
            options={
                'verbose_name': 'Asignación de Costo Directo',
                'verbose_name_plural': 'Asignaciones de Costos Directos',
                'ordering': ['provider_invoice', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='providerinvoice',
            index=models.Index(fields=['service_order', 'status'], name='transfers_p_service_af0302_idx'),
        ),
        migrations.AddIndex(
            model_name='providerinvoice',
            index=models.Index(fields=['provider', 'issue_date'], name='transfers_p_provide_9d3538_idx'),
        ),
    ]
