# Generated by Django 5.0.1 on 2026-01-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0017_billing_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='customer_iva_type',
            field=models.CharField(choices=[('gravado', 'Gravado (13% IVA)'), ('exento', 'Exento'), ('no_sujeto', 'No Sujeto (Exportación)')], default='no_sujeto', help_text='Tipo de IVA a aplicar al cobrar este gasto al cliente', max_length=20, verbose_name='Tratamiento Fiscal Cliente'),
        ),
    ]
