# Generated by Django 5.0.1 on 2026-01-11 02:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0018_alter_transfer_customer_iva_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='customer_markup_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Margen Cobro Cliente %'),
        ),
    ]
