# Generated by Django 5.0.1 on 2026-01-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0019_alter_transfer_customer_markup_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='providercreditnote',
            name='generation_code',
            field=models.CharField(blank=True, help_text='Código de generación DTE', max_length=100, null=True, verbose_name='Código de Generación'),
        ),
        migrations.AddField(
            model_name='providercreditnote',
            name='reception_stamp',
            field=models.CharField(blank=True, help_text='Sello de recepción DTE', max_length=100, null=True, verbose_name='Sello de Recepción'),
        ),
        migrations.AddField(
            model_name='providerinvoice',
            name='generation_code',
            field=models.CharField(blank=True, help_text='Código de generación DTE', max_length=100, null=True, verbose_name='Código de Generación'),
        ),
        migrations.AddField(
            model_name='providerinvoice',
            name='reception_stamp',
            field=models.CharField(blank=True, help_text='Sello de recepción DTE', max_length=100, null=True, verbose_name='Sello de Recepción'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='generation_code',
            field=models.CharField(blank=True, help_text='Código de generación DTE', max_length=100, null=True, verbose_name='Código de Generación'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='reception_stamp',
            field=models.CharField(blank=True, help_text='Sello de recepción DTE', max_length=100, null=True, verbose_name='Sello de Recepción'),
        ),
    ]
