# Generated by Django 5.0.1 on 2026-03-06 01:10

import apps.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0020_providercreditnote_generation_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderInvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Pagado')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Pago')),
                ('payment_method', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta')], default='transferencia', max_length=20, verbose_name='Método de Pago')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Referencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='provider_invoices/payments/', validators=[apps.validators.validate_document_file], verbose_name='Comprobante de Pago')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('provider_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_payments', to='transfers.providerinvoice', verbose_name='Factura de Proveedor')),
            ],
            options={
                'verbose_name': 'Pago a Factura de Proveedor',
                'verbose_name_plural': 'Pagos a Facturas de Proveedores',
                'ordering': ['-payment_date'],
            },
        ),
    ]
